from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any

class VideoModelBackend(ABC):
    @abstractmethod
    def load(self) -> None: ...
    @abstractmethod
    def unload(self) -> None: ...
    @abstractmethod
    def generate(self, request: Any, progress=None): ...
    @abstractmethod
    def supports_motion_control(self) -> bool: ...
    @abstractmethod
    def model_info(self) -> dict: ...
